spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.223.121:3306/shangou_db?serverTimezone=Asia/Shanghai  # 数据库的时区地址
    type: com.alibaba.druid.pool.DruidDataSource
  messages:
    basename: i18n/validate  #   验证文件的路径
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #统一进行日期格式的数据返回
    time-zone: Asia/Shanghai   # 默认时区
  servlet:
    multipart:
      max-file-size: 5MB  #单个文件最大5MB
      max-request-size: 100MB #一次请求最大一百兆
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #  下划线转换程驼峰
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #  日志也可以这么配置
  mapper-locations: classpath*:mybatis/mapper/**/*.xml  # mapper.xml文件的路径配置
server:
  servlet:
    context-path: /  # 这个是配置项目上下文路径
---

spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://localhost:3306/shangou_db?serverTimezone=Asia/Shanghai  # 数据库的时区地址
server:
  port: 80
---
spring:
  profiles: pro2
server:
  port: 8082
---
logging:
  level:
    com.lh.shangou.dao: info  #  线上环境是info
spring:
  profiles: pro3
server:
  port: 8083


---
logging:
  level:
    com.lh.shangou.dao: trace  #   开发环境的时候，dao包输出的日志级别是trace
spring:
  profiles: dev
server:
  port: 80
